import Head from "next/head";
import React from "react";
import ContactUs from "../../components/ContactUs/ContactUs";

const index = () => {
  return (
    <>
      <Head>
        <title>MTT - Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactUs />
    </>
  );
};

export default index;
