import React from "react";
import Head from "next/head";
import PageHeader from "../../components/layouts/PageHeader/PageHeader";
import SerachBar from "../../components/Notice/SearchBar/SerachBar";
import Logo from "../../components/Home/LOGO-Caro/Logo";

const index = () => {
  return (
    <>
      <Head>
        <title>MTT - Notice Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader title="Notice Board" />
      <SerachBar />
      <Logo />
    </>
  );
};

export default index;
