import React from "react";
import Head from "next/head";
import PageHeader from "../../components/layouts/PageHeader/PageHeader";
import Flight from "../../components/Flight/Flight";

const index = () => {
  return (
    <>
      <Head>
        <title>MTT - Hajj & Umrah | Gallary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader title="Book your Flight" key={0} />
      <Flight />
    </>
  );
};

export default index;
