import Head from "next/head";
import React from "react";
import MeetHono from "../../components/AboutUs/MeetHono/MeetHono";
import MeetOurTeam from "../../components/AboutUs/MeetTeam/MeetOurTeam";
import OldVision from "../../components/AboutUs/OldVision/OldVision";
import WeAre from "../../components/AboutUs/WeAre/WeAre";
import PageHeader from "../../components/layouts/PageHeader/PageHeader";
import Logo from "../../components/Home/LOGO-Caro/Logo";

const index = () => {
  return (
    <>
      <Head>
        <title>MTT - About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader title="About Us" />
      <WeAre />
      <OldVision />
      <MeetOurTeam />
      <MeetHono />
      <Logo />
    </>
  );
};

export default index;
