import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Box,
  Button,
  Card,
  CardBody,
  CardFooter,
  Container,
  Divider,
  Flex,
  Heading,
  Icon,
  IconButton,
  Image,
  Stack,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import HeaderCard from "../../components/Package-details/HeaderCard";
import NavBar from "../../components/Package-details/NavBar";
import PageHeader from "../../components/layouts/PageHeader/PageHeader";
import { MdOutlineGppGood, MdStarOutline } from "react-icons/md";

import { BiTimeFive, BiCheckSquare, BiPlus } from "react-icons/bi";
import { FiPhoneCall } from "react-icons/fi";

import { BsArrowRight, BsCheckSquare } from "react-icons/bs";
import { HiOutlineDocumentText, HiOutlineLocationMarker } from "react-icons/hi";
import { CgCloseR } from "react-icons/cg";
import { GrLocation } from "react-icons/gr";
const PackageDetails = () => {
  return (
    <>
      <Head>
        <title>MTT - Mirpur Tours & Travels - package</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader />
      <Container maxW="container.lg">
        <Flex justify="end">
          <HeaderCard />
        </Flex>
        <NavBar />
        <Flex mt={7} direction={{ base: "column", lg: "row" }} gap={2}>
          <Stack flex={2} spacing={5}>
            <Flex align="center" gap={3}>
              <Flex
                backgroundColor="purple.100"
                width="60px"
                height="70px"
                justify="center"
                align="center"
                rounded="md"
              >
                <Icon
                  as={HiOutlineDocumentText}
                  fontSize="4xl"
                  color="purple.400"
                />
              </Flex>
              <Heading fontSize="28px" fontWeight={700}>
                Haji Details
              </Heading>
            </Flex>
            <Flex flexWrap="wrap" gap={4}>
              <Box
                border="1px"
                borderColor="blue.400"
                borderRadius="4px"
                padding="8px"
              >
                <Text fontSize="14px" fontWeight={500}>
                  4-Star Royal Nozol Inn Hotel in Madinah
                </Text>
              </Box>
              <Box
                border="1px"
                borderColor="blue.400"
                borderRadius="4px"
                padding="8px"
              >
                <Text fontSize="14px" fontWeight={500}>
                  North America Mena Camp
                </Text>
              </Box>
              <Box
                border="1px"
                borderColor="blue.400"
                borderRadius="4px"
                padding="8px"
              >
                <Text fontSize="14px" fontWeight={500}>
                  4-Star Royal Nozol Inn Hotel in Madinah
                </Text>
              </Box>
            </Flex>
            <article>
              <Text fontSize="16px" lineHeight="27.2px">
                The Hajj- “pilgrimage” is an annual Islamic pilgrimage to Mecca,
                the most holy city of the Muslims, and a mandatory religious
                duty for Muslims that must be carried out at least once in their
                lifetime by all adult Muslims who are physically and financially
                capable of undertaking the journey, and can support their family
                during their absence.
              </Text>
              <br />
              <Text fontSize="16px" lineHeight="27.2px">
                It is one of the five pillars of Islam, alongside Shahadah,
                Salat, Zakat, and Sawm. The Hajj is the largest annual gathering
                of people in the world. The state of being physically and
                financially capable of performing the Hajj is called istita’ah,
                and a Muslim who fulfills this condition is called a mustati.
                The Hajj is a demonstration of the solidarity of the Muslim
                people, and their submission to God (Allah).
              </Text>
              <br />

              <Text fontSize="16px" lineHeight="27.2px">
                The word Hajj means “to intend a journey”, which connotes both
                the outward act of a journey and the inward act of intentions.
              </Text>
            </article>

            <Stack px={3} pt={5} spacing={5}>
              <Card direction={{ base: "column", sm: "row" }} shadow="lg">
                <Flex
                  width={{ base: "full", md: "130px" }}
                  padding={{ base: 2, md: 0 }}
                  backgroundColor="#D3F2ED"
                  h="100%"
                  justify="center"
                  align="center"
                >
                  <Image
                    src="/img/flight-icon.png"
                    height="60px"
                    w="60px"
                    objectFit="cover"
                  />
                </Flex>
                <CardBody p={7}>
                  <Heading size="18px" fontWeight={700} mb={5}>
                    Flight Info
                  </Heading>
                  <Stack spacing={4}>
                    <Flex gap={2}>
                      <Icon
                        as={BiCheckSquare}
                        fontSize="xl"
                        color="success.main"
                      />
                      <Text>
                        Tentative departure from the US July 21st, 2020.
                      </Text>
                    </Flex>
                    <Flex gap={2}>
                      <Icon
                        as={BiCheckSquare}
                        fontSize="xl"
                        color="success.main"
                      />
                      <Text align="start">
                        Tentative departure from Saudi Arabia August 5th/6th,
                        2020.
                      </Text>
                    </Flex>
                  </Stack>
                </CardBody>
              </Card>
              <Card direction={{ base: "column", sm: "row" }} shadow="lg">
                <Flex
                  width={{ base: "full", md: "130px" }}
                  padding={{ base: 2, md: 0 }}
                  backgroundColor="purple.100"
                  h="full"
                  justify="center"
                  align="center"
                >
                  <Image
                    src="/img/time-icon.png"
                    height="60px"
                    w="60px"
                    objectFit="cover"
                  />
                </Flex>
                <CardBody p={7}>
                  <Heading size="18px" fontWeight={700} mb={5}>
                    Departure Time
                  </Heading>
                  <Stack spacing={4}>
                    <Flex gap={2}>
                      <Icon
                        as={BiCheckSquare}
                        fontSize="xl"
                        color="success.main"
                      />
                      <Text>3 Hours Before Flight Time.</Text>
                    </Flex>
                  </Stack>
                </CardBody>
              </Card>
              <Card
                direction={{ base: "column", sm: "row" }}
                shadow="lg"
                rounded="lg"
              >
                <Flex
                  width={{ base: "full", md: "130px" }}
                  padding={{ base: 2, md: 0 }}
                  backgroundColor="blue.100"
                  h="full"
                  justify="center"
                  align="center"
                >
                  <Image
                    src="/img/add-icon.png"
                    height="60px"
                    w="60px"
                    objectFit="cover"
                  />
                </Flex>
                <CardBody p={7}>
                  <Heading size="18px" fontWeight={700} mb={5}>
                    Addition
                  </Heading>
                  <Stack spacing={4}>
                    <Flex gap={2}>
                      <Icon
                        as={BiCheckSquare}
                        fontSize="xl"
                        color="success.main"
                      />
                      <Text>
                        Muslim Scholar/Leader will accompany the group.
                      </Text>
                    </Flex>
                    <Flex gap={2}>
                      <Icon
                        as={BiCheckSquare}
                        fontSize="xl"
                        color="success.main"
                      />
                      <Text>Visit to historic sites at Medina.</Text>
                    </Flex>
                  </Stack>
                </CardBody>
              </Card>
              <Card
                direction={{ base: "column", sm: "row" }}
                shadow="lg"
                rounded="lg"
              >
                <Flex
                  width={{ base: "full", md: "130px" }}
                  padding={{ base: 2, md: 0 }}
                  backgroundColor="red.100"
                  h="full"
                  justify="center"
                  align="center"
                >
                  <Image
                    src="/img/price-icon.png"
                    height="60px"
                    w="60px"
                    objectFit="cover"
                  />
                </Flex>
                <CardBody p={7}>
                  <Heading size="18px" fontWeight={700} mb={5}>
                    Price Excludes
                  </Heading>
                  <Stack spacing={4}>
                    <Flex gap={2}>
                      <Icon as={CgCloseR} fontSize="xl" color="error.main" />
                      <Text>
                        Hajj Service fees to the Unified Offices and Visa
                        processing (about $500 cost).
                      </Text>
                    </Flex>
                    <Flex gap={2}>
                      <Icon as={CgCloseR} fontSize="xl" color="error.main" />
                      <Text>Cost of zabiha/sacrifice (about $150)</Text>
                    </Flex>
                    <Flex gap={2}>
                      <Icon as={CgCloseR} fontSize="xl" color="error.main" />
                      <Text>
                        Any additional charges related to stopover to other
                        destinations other than Saudi Arabia
                      </Text>
                    </Flex>
                  </Stack>
                </CardBody>
              </Card>
            </Stack>
            <Divider />

            <Flex align="center" gap={3}>
              <Flex
                backgroundColor="purple.100"
                width="60px"
                height="70px"
                justify="center"
                align="center"
                rounded="md"
              >
                <Icon
                  as={HiOutlineLocationMarker}
                  fontSize="4xl"
                  color="purple.400"
                />
              </Flex>
              <Heading fontSize="28px" fontWeight={700}>
                Itinerary
              </Heading>
            </Flex>
            <Heading>Continue from here</Heading>
          </Stack>
          <Stack flex={1} spacing={7}>
            <Card padding={6} bg="white" shadow="lg">
              <Text fontWeight={700} mb={8}>
                Why Book With Us?
              </Text>
              <Stack spacing={4}>
                <Flex align="center" gap={2}>
                  <Icon
                    as={MdOutlineGppGood}
                    color="success.100"
                    fontSize="24px"
                  />
                  <Text fontSize="16px">Best price guarantee</Text>
                </Flex>
                <Flex align="center" gap={2}>
                  <Icon as={BiTimeFive} color="warning.100" fontSize="24px" />
                  <Text fontSize="16px">24/7 Supports</Text>
                </Flex>
                <Flex align="center" gap={2}>
                  <Icon
                    as={MdStarOutline}
                    color="success.100"
                    fontSize="24px"
                  />
                  <Text fontSize="16px">Hand-packed Tours & Activities</Text>
                </Flex>
              </Stack>
            </Card>
            <Card padding={6} bg="white" shadow="lg">
              <Text fontWeight={700} mb={8}>
                Get a Question?
              </Text>
              <Stack spacing={6}>
                <Text fontSize="16px" lineHeight="150%">
                  Do not hesitage to give us a call. We are an expert team and
                  we are happy to talk to you.
                </Text>
                <Flex align="center" gap={2}>
                  <Icon as={FiPhoneCall} color="warning.100" fontSize="24px" />
                  <Text fontSize="16px">+0881 98887799</Text>
                </Flex>
                <Box px={4}>
                  <Button
                    size="lg"
                    color="white"
                    bg="primary.200"
                    colorScheme="yellow"
                    w="full"
                    rightIcon={<BsArrowRight />}
                  >
                    Email
                  </Button>
                </Box>
              </Stack>
            </Card>
          </Stack>
        </Flex>
      </Container>
    </>
  );
};

export default PackageDetails;
