import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "../components/Home/Hero/Hero";
import About from "../components/About/About";
import Package from "../components/Home/Package/Package";
import Testimonial from "../components/Home/Testimonial/Testimonial";
import Guide from "../components/Home/Guide-Banner/Guide";
import Artical from "../components/Home/Artical/Artical";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MTT - Mirpur Tours & Travels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Package />
      <Testimonial />
      <Guide />
      <Artical />
    </>
  );
}
